runtime: static
handlers:
  - url: /scripts
    static_dir: scripts
  - url: /styles
    static_dir: styles
  - url: /(.*\.html)
    static_files: \1
    upload: .*\.html
  - url: /
    static_files: index.html
    upload: index.html
