steps:
  # Build dengan Buildpack untuk Cloud Run (tanpa Docker)
  - name: gcr.io/buildpacks/builder
    args:
      [
        "pack",
        "build",
        "gcr.io/$PROJECT_ID/tcc-be",
        "--builder",
        "gcr.io/buildpacks/builder:v1",
        "--path",
        "./backend"
      ]

  # Push image ke Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/tcc-be"]

  # Deploy ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "be",
        "--image",
        "gcr.io/$PROJECT_ID/tcc-be",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--allow-unauthenticated"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
